# Generated by Django 4.1 on 2022-08-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='estoque_max',
            new_name='estoque_min',
        ),
    ]
