# Generated by Django 4.1 on 2022-08-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_rename_estoque_max_produto_estoque_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='descricao',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=7),
        ),
    ]
