# Generated by Django 4.1 on 2022-08-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_movimento_produto_alter_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('Un', 'Un'), ('Kg', 'Kg'), ('g', 'g'), ('Lt', 'Lt'), ('ml', 'ml')], max_length=2),
        ),
    ]
